# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Datakit < Formula
  desc "Software to create fast and easy drum rolls."
  homepage "https://datakit.guance.io/"
  version "1.6.0-alpha"
  license "MIT"

  on_macos do
    url "https://github.com/GuanceCloud/datakit/releases/download/v1.6.0-alpha/datakit_1.6.0-alpha_darwin_amd64.zip", using: CurlDownloadStrategy
    sha256 "5ebfb0eefbe13e9e19e818d5d5e9b63068f05f06426449382702bf1f3d298f3d"

    def install
      bin.install "datakit"
      # ...
    end

    if Hardware::CPU.arm?
      def caveats
        <<~EOS
          The darwin_arm64 architecture is not supported for the Datakit
          formula at this time. The darwin_amd64 binary may work in compatibility
          mode, but it might not be fully supported.
        EOS
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/GuanceCloud/datakit/releases/download/v1.6.0-alpha/datakit_1.6.0-alpha_linux_amd64.zip", using: CurlDownloadStrategy
      sha256 "9dee5204086886af6e5ca98b62b0b3b99146e8ec6bcb843a639669e83b4c0d16"

      def install
        bin.install "datakit"
        # ...
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/GuanceCloud/datakit/releases/download/v1.6.0-alpha/datakit_1.6.0-alpha_linux_arm.zip", using: CurlDownloadStrategy
      sha256 "ad5bb4df68eaa02ba0b68b51715186c157ada164d51cebe0480fb9bd9a9078ad"

      def install
        bin.install "datakit"
        # ...
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/GuanceCloud/datakit/releases/download/v1.6.0-alpha/datakit_1.6.0-alpha_linux_arm64.zip", using: CurlDownloadStrategy
      sha256 "7db7175112967c6fff6648851a3535a2bbd7a31b8afde34d7827adc0707d9c92"

      def install
        bin.install "datakit"
        # ...
      end
    end
  end

  test do
    system "#{bin}/datakit version"
    # ...
  end
end
