# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Datakit < Formula
  desc "Software to create fast and easy drum rolls."
  homepage "https://datakit.guance.io/"
  version "1.6.3-alpha"
  license "MIT"

  on_macos do
    url "https://github.com/GuanceCloud/datakit/releases/download/v1.6.3-alpha/datakit_1.6.3-alpha_darwin_amd64.zip", using: CurlDownloadStrategy
    sha256 "0be4adfe4679bfb782f303ad96ebade687c1f670241dbfa06ee0f0aa69b75019"

    def install
      bin.install "datakit"
      # ...
    end

    if Hardware::CPU.arm?
      def caveats
        <<~EOS
          The darwin_arm64 architecture is not supported for the Datakit
          formula at this time. The darwin_amd64 binary may work in compatibility
          mode, but it might not be fully supported.
        EOS
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/GuanceCloud/datakit/releases/download/v1.6.3-alpha/datakit_1.6.3-alpha_linux_amd64.zip", using: CurlDownloadStrategy
      sha256 "d1887ee67fbd96de3076f976a4f39ae05c2c99e508a356e5c2c565f786268e14"

      def install
        bin.install "datakit"
        # ...
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/GuanceCloud/datakit/releases/download/v1.6.3-alpha/datakit_1.6.3-alpha_linux_arm.zip", using: CurlDownloadStrategy
      sha256 "be11c610d6c4e31cc608daf2651722e64f9d1f436a62eab91659422e496f5e23"

      def install
        bin.install "datakit"
        # ...
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/GuanceCloud/datakit/releases/download/v1.6.3-alpha/datakit_1.6.3-alpha_linux_arm64.zip", using: CurlDownloadStrategy
      sha256 "11d4334f59b60d839e231bfa3b8b43e599a3ba6e7f4c51b3e9feaaeed947a374"

      def install
        bin.install "datakit"
        # ...
      end
    end
  end

  test do
    system "#{bin}/datakit version"
    # ...
  end
end
