# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Platypus < Formula
  desc "Software to create fast and easy drum rolls."
  homepage "https://platypus.guance.io/"
  version "0.2.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/GuanceCloud/platypus/releases/download/v0.2.0/platypus_0.2.0_darwin_amd64.tar.gz", using: CurlDownloadStrategy
      sha256 "aa6c9ba943b351c5b8c59343ec8712779472edb2f558894090f1ee9234a75e97"

      def install
        bin.install "platypus"
        # ...
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/GuanceCloud/platypus/releases/download/v0.2.0/platypus_0.2.0_darwin_arm64.tar.gz", using: CurlDownloadStrategy
      sha256 "b4f3948eac76c383d2125ccfff056fc1d193082781d6d60131d955d6436668ea"

      def install
        bin.install "platypus"
        # ...
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/GuanceCloud/platypus/releases/download/v0.2.0/platypus_0.2.0_linux_arm64.tar.gz", using: CurlDownloadStrategy
      sha256 "f91f0081cf3aad54ae116e9ed7eebf2d8a830f8527b831181dce943c132488c8"

      def install
        bin.install "platypus"
        # ...
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/GuanceCloud/platypus/releases/download/v0.2.0/platypus_0.2.0_linux_amd64.tar.gz", using: CurlDownloadStrategy
      sha256 "d35de9086cc80a9bea17b80d9b057d8df718807f24678e6033ba9ef3523a94fe"

      def install
        bin.install "platypus"
        # ...
      end
    end
  end

  test do
    system "#{bin}/platypus version"
    # ...
  end
end
