# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Platypus < Formula
  desc "Software to create fast and easy drum rolls."
  homepage "https://platypus.guance.io/"
  version "0.2.3"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/GuanceCloud/platypus/releases/download/v0.2.3/platypus_0.2.3_darwin_arm64.tar.gz", using: CurlDownloadStrategy
      sha256 "71dfb7ef883b61b820efae8b12e80e63f799c2221be40cdaff7008c996031e87"

      def install
        bin.install "platypus"
        # ...
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/GuanceCloud/platypus/releases/download/v0.2.3/platypus_0.2.3_darwin_amd64.tar.gz", using: CurlDownloadStrategy
      sha256 "21be25c2d614fd3e95ed6b20b082de2b148bdf5b3d4870944b9c132ea2649dd2"

      def install
        bin.install "platypus"
        # ...
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/GuanceCloud/platypus/releases/download/v0.2.3/platypus_0.2.3_linux_amd64.tar.gz", using: CurlDownloadStrategy
      sha256 "b4193248e88d223f77d1c5b50fc2ae2a42038d01714bf2068b55640a4f99daf8"

      def install
        bin.install "platypus"
        # ...
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/GuanceCloud/platypus/releases/download/v0.2.3/platypus_0.2.3_linux_arm64.tar.gz", using: CurlDownloadStrategy
      sha256 "7a97db688430d6ee1ed73c02bc3dade54fbeb5339f86982d0d71fdec6f43e198"

      def install
        bin.install "platypus"
        # ...
      end
    end
  end

  test do
    system "#{bin}/platypus version"
    # ...
  end
end
